# Generated by Django 3.0.5 on 2020-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeMetadata',
            fields=[
                ('videoId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('publishTimestamp', models.DateTimeField(verbose_name='Date published')),
                ('thumbnailUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
