# Generated by Django 3.0.5 on 2020-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubemetadata',
            name='publishTimestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
