# Generated by Django 3.0.5 on 2020-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200417_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubemetadata',
            name='publishTimestamp',
            field=models.DateTimeField(verbose_name='Publish Timestamp'),
        ),
        migrations.AddIndex(
            model_name='youtubemetadata',
            index=models.Index(fields=['-publishTimestamp'], name='youtube_you_publish_ede8d7_idx'),
        ),
    ]
